name: jsonplaceholder_client
description: A jsonplaceholder client for Dart.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.1
  fresh_dio:
    path: ../../../
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1
